//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCNet.Community.Plugins.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCNet.Community.Plugins.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; was not found..
        /// </summary>
        internal static string FileNotFoundMessage {
            get {
                return ResourceManager.GetString("FileNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^((d|-)[^\s]+)\s+(\d{1,})\s+([^\s]+)\s+([^\s]+)\s+(\d{1,})\s+([a-z]{3}\s+\d{1,2}\s+\d{1,2} :? \d{2})\s+([^\n]+)$.
        /// </summary>
        internal static string FtpDirectoryListRegexPattern {
            get {
                return ResourceManager.GetString("FtpDirectoryListRegexPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rss Builds Publisher plugin for CruiseControl.NET version {0} - by Ryan Conrad - http://codeplex.com/ccnetplugins.
        /// </summary>
        internal static string GeneratorString {
            get {
                return ResourceManager.GetString("GeneratorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ccp.*.macro.dll.
        /// </summary>
        internal static string MacroDllPattern {
            get {
                return ResourceManager.GetString("MacroDllPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro already loaded with the name &apos;{0}&apos;.
        /// </summary>
        internal static string MacroLoadedMessage {
            get {
                return ResourceManager.GetString("MacroLoadedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro Error: Macro &apos;{0}&apos; was not found..
        /// </summary>
        internal static string MacroNotFoundMessage {
            get {
                return ResourceManager.GetString("MacroNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @\{\s?([^\(]*?)\s?\(\s?(.*?)\s?\)\s?\}.
        /// </summary>
        internal static string MacroPattern {
            get {
                return ResourceManager.GetString("MacroPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \$\(([^\)]+)\).
        /// </summary>
        internal static string PropertyPatern {
            get {
                return ResourceManager.GetString("PropertyPatern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SSH Ftp protocol is not supported. For secured ftp requests, ftps ( ftp over ssl) can be used..
        /// </summary>
        internal static string SshFtpNotSupportedMessage {
            get {
                return ResourceManager.GetString("SshFtpNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !\{([^\}]+)\}.
        /// </summary>
        internal static string XPathPattern {
            get {
                return ResourceManager.GetString("XPathPattern", resourceCulture);
            }
        }
    }
}
