//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCNet.Community.Plugins.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{6} {2}: {5}")]
        public string MetaWeblogDefaultTitleFormat {
            get {
                return ((string)(this["MetaWeblogDefaultTitleFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<h4>{6} {2}: {5}</h4><h5>Status</h5>{7}<br /><h5>Modifications</h5>{0}<br /><h5>R" +
            "esults</h5>{1}<br /><h5>Last Changeset Number</h5>{3}<br /><h5>Total Integration" +
            " Time</h5>{4}<br />\r\n<div class=\"tags\"><span class=\"tagsLabel\">Tags:</span>{8}</" +
            "div>")]
        public string MetaWeblogDefaultDescriptionFormat {
            get {
                return ((string)(this["MetaWeblogDefaultDescriptionFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ <a rel=\"tag\" href=\"http://technorati.com/tag/{0}\">{0}</a> ]")]
        public string MetaWeblogDefaultTagFormat {
            get {
                return ((string)(this["MetaWeblogDefaultTagFormat"]));
            }
        }
    }
}
